### ISSUE TITLE
Tutorial for this project

### ISSUE THREAD

**Issue by saqlain38** [parithoshpoojary/soldiers-health-monitoring-and-position-tracking-system#1]
Can you please give a tutorial explaining which  code is used in which connection. the Readme.txt file has very little information. Would really appreciate the help. In very much need. Thanks

**Comment by 19-ade** [comment]
The level 1 implementation folder has the level-1_implementation__all_sensors_.ino file . This contains the final code taking into account all the sensors used : 
- LM 35 for temperature connected to Analog pin A1
- Pulse sensor connected to analog pin
- GPS and HC-12 connected to digital pins
He also created variables samplesUntilReport,  SAMPLES_PER_SERIAL_SAMPLES and contor_apelare to keep track of the cycles of readings. Each sensor reading is triggered after a certain number of cycles . 

In the void loop() he has defined these function definitions to read each data. 

Hope this tiny intro helps :)

**Comment by parithoshpoojary** [comment]
Restructured the README file accordingly to the project and also thrown in some information/explanation regarding the project.
Hope this helps :)
