### ISSUE TITLE
Which sensors you used particularly? there serial no. like sx1278 of which company. 
Please add images of those sensors or else refer links to buy it.

### ISSUE THREAD

**Issue by shaikkareemuddin** [parithoshpoojary/soldiers-health-monitoring-and-position-tracking-system#5]

**Comment by parithoshpoojary** [comment]
Please find the links to purchase the sensors below: 

* Temperature Sensor (LM-35) - https://www.amazon.in/Robo-India-LM35-Temperature-Sensor/dp/B00WO5AFPE

* Pulse Sensor (RC-A-4015) - https://www.amazon.in/Robocraze-Heart-Pulse-Sensor-Module/dp/B07DWQ8WWH/ref=sr_1_3?keywords=rc-a-4015&qid=1641623815&sr=8-3

* GPS Sensor (Neo-6M) - https://www.amazon.in/Generic-Ublox-NEO-6M-GPS-Module/dp/B089QV75YY/ref=sr_1_1?crid=XQHEYJR8YTVH&keywords=neo-6m&qid=1641623890&sprefix=neo%2Caps%2C647&sr=8-1

**Wireless Modules**
* HC-12 - https://www.amazon.in/Robocraze-433Mhz-Wireless-Replace-Bluetooth/dp/B08F78LCYX/ref=sr_1_2?crid=63PNDOYQ7NMF&keywords=HC-12&qid=1641623956&sprefix=hc%2Caps%2C460&sr=8-2 

    **SX-1278 Flipkart Link**
* SX-1278 - https://www.flipkart.com/robokitshop-ra-01-long-range-wireless-transceiver-sx1278-433mhz-radio-electronic-hobby-kit/p/itmfh2kzz4hu7xnx?pid=DHYFH2HFZCC3A7XW&lid=LSTDHYFH2HFZCC3A7XWCROVLO&marketplace=FLIPKART&q=sx-1278+&store=search.flipkart.com&srno=s_1_1&otracker=search&otracker1=search&fm=SEARCH&iid=c3feb873-b56a-43c2-9037-4de6f9259345.DHYFH2HFZCC3A7XW.SEARCH&ppt=hp&ppn=homepage&ssid=r898c8dmfo1fgef41641624080253&qH=9e5186915bc59986

    **SX-1278 Amazon Link**
Note: In the amazon link you will have to buy an antenna separately.
* SX-1278 - https://www.amazon.in/SX1278-433MHz-Wireless-Spectrum-Transmission/dp/B08SHQRGD8
